### PR TITLE
Critical Bug fixes and Latest PR's

### PR DESCRIPTION
**Pull request by danoli3**
Fixes:  Critical Bug for saveScoreToReportLater https://github.com/nihalahmed/GameCenterManager/issues/52
Fixes: https://github.com/nihalahmed/GameCenterManager/issues/44

Adds: https://github.com/nihalahmed/GameCenterManager/pull/47

### CODE REVIEW

**Comment by danoli3** [comment]
@Sam-Spencer @nihalahmed This needs urgent review.

**Comment by bertrandserres** [comment]
Hi,

Thanks for this fix. I've just tried to use it in my app because I was not able to use the method 'saveAndReportAchievement' (error : no bundle for bundleID: (null))

With this fix, I can unlock required achievements, even if the error message is still displayed in the logs console.

But now the notification is not displayed even if the param 'shouldDisplayNotification' is set to 'YES'. Can you tell me if you can reproduce this bug please ?

Thanks,

**Comment by Sam-Spencer** [comment]
Thanks for the pull request! I'll take a look at it right now and get back to you as soon as possible @danoli3.

**Comment by danoli3** [comment]
@Sam-Spencer Thanks for merging and checking this all out!

**Pull request merged**
